services:
  - type: web
    name: noa-caffe-menu
    runtime: node
    buildCommand: echo "ready"
    startCommand: node server.js
    healthCheckPath: /ping
    envVars:
      - key: PUBLIC_URL
        value: https://noa-caffe-menu.onrender.com
      - key: SUPABASE_URL
        value: https://pyxcgtsbjyvifpafqdjv.supabase.co
